# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "1.0.0-rc.2"

  on_macos do
    on_intel do
      sha256 "f973dd6106d2bc1a65c619c84fb17c12b74abca0c51e9b33c29c9cfdbf36c785"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6896371344f68504dea3225618b840cb1d785a7296d7e4151e279e5080924faf"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab464cefb07ffd144087d8dfb9fa14f192bc06637f82e79090e9be8a0989ffd0"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6195f53c81acd4fa9028f944517186d80bb5c0932193626a1f846e54dd4eb1c7"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
  end

  name "engram"
  desc "지식관리 위키의 승급 파이프라인을 강제하는 단일 Go 바이너리"
  homepage "https://github.com/neocode24/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required

end
