# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "282ca709a4b109163ad73fccac9660320ec2788849c442c1b6d479e87caa6e17"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c91ea054e37f094bfec8d954090dc7b05b04c53de08efeeebe1c26d89ec68ef"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c41bbdc07b15f190699bb12538f4a338a4e70e1f5ac5ae3afe0ee4a918a57b04"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b6c1ae7749ee46723796911f72865ee7b140e28ea800831e72d3c91c1e3b4e2"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
  end

  name "engram"
  desc "지식관리 위키의 승급 파이프라인을 강제하는 단일 Go 바이너리"
  homepage "https://github.com/neocode24/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required

end
