# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "1.0.0-rc.1"

  on_macos do
    on_intel do
      sha256 "506ff57506afdc87d8714f4de11abdd71b4a90d62f0bcefa1d276a2b2f272fbb"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69a4cfeaf50bee1fbdfbfa09abd1f1f26188f44147049815d529782311eac5c1"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d20c4cfb5652718e347ad3b7b5f82ca877bb5017e5ed5d46ad967d8801ad723"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b6d67874cdd2d85ca857c1a3301dc817a55a9c12cdd11cb107df3326a8760ef"
      url "https://github.com/neocode24/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
  end

  name "engram"
  desc "지식관리 위키의 승급 파이프라인을 강제하는 단일 Go 바이너리"
  homepage "https://github.com/neocode24/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required

end
